apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardapioinfra
  namespace: monitoring
  labels:
    app: cardapioinfra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cardapioinfra
  template:
    metadata:
      labels:
        app: cardapioinfra
    spec:
      containers:
        - name: cardapioinfra
          # todo: salvar imagem no dockerhub
          # image: b1tech/cardapioinfra:latest 
          ports:
            - containerPort: 8092
            - containerPort: 8093
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
